# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CheckBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, image_url: str=None):  # noqa: E501
        """CheckBody - a model defined in Swagger

        :param image_url: The image_url of this CheckBody.  # noqa: E501
        :type image_url: str
        """
        self.swagger_types = {
            'image_url': str
        }

        self.attribute_map = {
            'image_url': 'imageUrl'
        }

        self._image_url = image_url

    @classmethod
    def from_dict(cls, dikt) -> 'CheckBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CheckBody of this CheckBody.  # noqa: E501
        :rtype: CheckBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_url(self) -> str:
        """Gets the image_url of this CheckBody.


        :return: The image_url of this CheckBody.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this CheckBody.


        :param image_url: The image_url of this CheckBody.
        :type image_url: str
        """

        self._image_url = image_url
